/* 
A list of all of the K.K. Songs.
Used for reference so the extension can easily know the song name and game each song came from.
Also used to make the songs more human-readable.
*/

const liveKKSongList = [
    'AC - Aloha K.K.',
    'AC - Cafe K.K.',
    'AC - Comrade K.K.',
    'AC - DJ K.K.',
    'AC - Go K.K. Rider!',
    'AC - I Love You',
    'AC - Imperial K.K.',
    'AC - K.K. Aria',
    'AC - K.K. Ballad',
    'AC - K.K. Blues',
    'AC - K.K. Bossa',
    'AC - K.K. Calypso',
    'AC - K.K. Casbah',
    'AC - K.K. Chorale',
    'AC - K.K. Condor',
    'AC - K.K. Country',
    "AC - K.K. Cruisin'",
    'AC - K.K. D & B',
    'AC - K.K. Dirge',
    'AC - K.K. Etude',
    'AC - K.K. Faire',
    'AC - K.K. Folk',
    'AC - K.K. Fusion',
    'AC - K.K. Gumbo',
    'AC - K.K. Jazz',
    'AC - K.K. Lament',
    'AC - K.K. Love Song',
    'AC - K.K. Lullaby',
    'AC - K.K. Mambo',
    'AC - K.K. March',
    'AC - K.K. Parade',
    'AC - K.K. Ragtime',
    'AC - K.K. Reggae',
    'AC - K.K. Rock',
    'AC - K.K. Safari',
    'AC - K.K. Salsa',
    'AC - K.K. Samba',
    'AC - K.K. Ska',
    'AC - K.K. Song',
    'AC - K.K. Soul',
    'AC - K.K. Steppe',
    'AC - K.K. Swing',
    'AC - K.K. Tango',
    'AC - K.K. Technopop',
    'AC - K.K. Waltz',
    'AC - K.K. Western',
    'AC - Lucky K.K.',
    'AC - Mr. K.K.',
    'AC - Only Me',
    "AC - Rockin' K.K.",
    'AC - Senor K.K.',
    'AC - Soulful K.K.',
    "AC - Surfin' K.K.",
    'AC - The K. Funk',
    'AC - Two Days Ago',
    'CF - Agent K.K.',
    'CF - Forest Life',
    'CF - K.K. Dixie',
    'CF - K.K. House',
    'CF - K.K. Marathon',
    'CF - K.K. Metal',
    'CF - K.K. Rally',
    'CF - K.K. Rockabilly',
    'CF - K.K. Sonata',
    'CF - King K.K.',
    'CF - Marine Song 2001',
    'CF - Mountain Song',
    'CF - My Place',
    'CF - Neapolitan',
    'CF - Pondering',
    'CF - Spring Blossoms',
    'CF - Stale Cupcakes',
    'CF - Steep Hill',
    'CF - To the Edge',
    'CF - Wandering'
];

const aircheckKKSongList = [
    'AC - Aloha K.K.',
    'AC - Cafe K.K.',
    'AC - Comrade K.K.',
    'AC - DJ K.K.',
    'AC - Go K.K. Rider!',
    'AC - I Love You',
    'AC - Imperial K.K.',
    'AC - K.K. Aria',
    'AC - K.K. Ballad',
    'AC - K.K. Blues',
    'AC - K.K. Bossa',
    'AC - K.K. Calypso',
    'AC - K.K. Casbah',
    'AC - K.K. Chorale',
    'AC - K.K. Condor',
    'AC - K.K. Country',
    "AC - K.K. Cruisin'",
    'AC - K.K. D & B',
    'AC - K.K. Dirge',
    'AC - K.K. Etude',
    'AC - K.K. Faire',
    'AC - K.K. Folk',
    'AC - K.K. Fusion',
    'AC - K.K. Gumbo',
    'AC - K.K. Jazz',
    'AC - K.K. Lament',
    'AC - K.K. Love Song',
    'AC - K.K. Lullaby',
    'AC - K.K. Mambo',
    'AC - K.K. March',
    'AC - K.K. Parade',
    'AC - K.K. Ragtime',
    'AC - K.K. Reggae',
    'AC - K.K. Rock',
    'AC - K.K. Safari',
    'AC - K.K. Salsa',
    'AC - K.K. Samba',
    'AC - K.K. Ska',
    'AC - K.K. Song',
    'AC - K.K. Soul',
    'AC - K.K. Steppe',
    'AC - K.K. Swing',
    'AC - K.K. Tango',
    'AC - K.K. Technopop',
    'AC - K.K. Waltz',
    'AC - K.K. Western',
    'AC - Lucky K.K.',
    'AC - Mr. K.K.',
    'AC - Only Me',
    "AC - Rockin' K.K.",
    'AC - Senor K.K.',
    'AC - Soulful K.K.',
    "AC - Surfin' K.K.",
    'AC - The K. Funk',
    'AC - Two Days Ago',
    'CF - Agent K.K.',
    'CF - Forest Life',
    'CF - K.K. Dixie',
    'CF - K.K. House',
    'CF - K.K. Marathon',
    'CF - K.K. Metal',
    'CF - K.K. Rally',
    'CF - K.K. Rockabilly',
    'CF - K.K. Sonata',
    'CF - King K.K.',
    'CF - Marine Song 2001',
    'CF - Mountain Song',
    'CF - My Place',
    'CF - Neapolitan',
    'CF - Pondering',
    'CF - Spring Blossoms',
    'CF - Stale Cupcakes',
    'CF - Steep Hill',
    'CF - To the Edge',
    'CF - Wandering'
  ];